### ISSUE TITLE
0.2.10 issues, Babel transpiler & weak account references.

### ISSUE THREAD

**Issue by robertpitt** [astronomerio/meteor-astronomer#14]
Hey, we are just testing the new 0.2.10 version and come across two issues.

The first is that `Accounts` is not in scope, as we use a package based development approach, we do not have `accounts-base` within the `.meteor/packages` file, it's individually references by each package in `packages/*` that require it.

So doing `api.use('accounts-base', {weak: true})` breaks down for projects using this approach (maybe seperate accounts into an extension package such as `astronomer:ext-accounts`).

The issue causes an undefined references `Accounts`:

```
I20150917-13:32:33.062(1)? Exception from sub id undefined ReferenceError: Accounts is not defined
I20150917-13:32:33.063(1)?     at [object Object].Package [as _handler] (packages/astronomerio:core/dist/publications.js:17:1)
I20150917-13:32:33.063(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150917-13:32:33.063(1)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20150917-13:32:33.063(1)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150917-13:32:33.063(1)?     at packages/ddp/livedata_server.js:407:1
I20150917-13:32:33.063(1)?     at Array.forEach (native)
I20150917-13:32:33.063(1)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150917-13:32:33.064(1)?     at [object Object]._.extend.startUniversalSubs (packages/ddp/livedata_server.js:406:1)
I20150917-13:32:33.064(1)?     at [object Object]._.extend._setUserId (packages/ddp/livedata_server.js:744:1)
I20150917-13:32:33.064(1)?     at [object Object].setUserId [as _setUserId] (packages/ddp/livedata_server.js:634:1)
```

Now, if I was to add `accounts-base` to `.meteor/packages` as  short term solution, I run into another issue with your babel compiler, as you are using a `for(let x in y)`, babel transpiles this to use  the `Symbol.iterator` which is a [polyfill implementation](http://babeljs.io/docs/usage/polyfill/).

Causing the following exception:

```
I20150917-14:35:45.478(1)? Exception from sub id undefined ReferenceError: Symbol is not defined
I20150917-14:35:45.478(1)?     at [object Object].Package [as _handler] (packages/astronomerio:core/dist/publications.js:23:1)
I20150917-14:35:45.478(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150917-14:35:45.478(1)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20150917-14:35:45.478(1)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150917-14:35:45.479(1)?     at packages/ddp/livedata_server.js:407:1
I20150917-14:35:45.479(1)?     at Array.forEach (native)
I20150917-14:35:45.479(1)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150917-14:35:45.479(1)?     at [object Object]._.extend.startUniversalSubs (packages/ddp/livedata_server.js:406:1)
I20150917-14:35:45.479(1)?     at [object Object]._.extend._setUserId (packages/ddp/livedata_server.js:744:1)
I20150917-14:35:45.479(1)?     at [object Object].setUserId [as _setUserId] (packages/ddp/livedata_server.js:634:1)
```

@peterchoo @robfallows

**Comment by ryw** [comment]
@schnie is back in the country on Sunday... he'll look at this ASAP

**Comment by robertpitt** [comment]
Bump, @ryw you taken a look at this yet?

Thanks

**Comment by ryw** [comment]
@schnie is back in town now, he'll take a look today...

**Comment by schnie** [comment]
Hey @robertpitt, just published 0.2.12.  Removed the `for of` loop and added a better check for accounts oauth packages.  Let me know how it goes!

**Comment by robertpitt** [comment]
Still getting this error guys

```
I20150921-22:37:30.267(1)? Exception from sub id undefined ReferenceError: Accounts is not defined
I20150921-22:37:30.267(1)?     at [object Object].Package [as _handler] (packages/astronomerio:core/dist/publications.js:18:1)
I20150921-22:37:30.268(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150921-22:37:30.268(1)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20150921-22:37:30.268(1)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150921-22:37:30.268(1)?     at packages/ddp/livedata_server.js:407:1
I20150921-22:37:30.269(1)?     at Array.forEach (native)
I20150921-22:37:30.269(1)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150921-22:37:30.269(1)?     at [object Object]._.extend.startUniversalSubs (packages/ddp/livedata_server.js:406:1)
I20150921-22:37:30.269(1)?     at [object Object]._.extend._setUserId (packages/ddp/livedata_server.js:744:1)
I20150921-22:37:30.269(1)?     at [object Object].setUserId [as _setUserId] (packages/ddp/livedata_server.js:634:1)
```

**Comment by schnie** [comment]
Ah, ok made a change to access the `Accounts` object through the `Package`
object.  Sorry about that.  v0.2.13 released with fix.

**Comment by robertpitt** [comment]
Nope, I now have this error

```
ReferenceError: Accounts is not defined
    at emailAddress (http://localhost:3000/packages/astronomerio_core.js?76a17c3d39867f50b1a58d6adbfab9a6d50d3d79:9901:30)
    at http://localhost:3000/packages/astronomerio_core.js?76a17c3d39867f50b1a58d6adbfab9a6d50d3d79:9931:25
    at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?21f0f4306879f57e10ad3a97efe9ea521c5b5775:308:36)
    at new Tracker.Computation (http://localhost:3000/packages/tracker.js?21f0f4306879f57e10ad3a97efe9ea521c5b5775:224:10)
    at Object.Tracker.autorun (http://localhost:3000/packages/tracker.js?21f0f4306879f57e10ad3a97efe9ea521c5b5775:499:11)
    at setupIdentify (http://localhost:3000/packages/astronomerio_core.js?76a17c3d39867f50b1a58d6adbfab9a6d50d3d79:9928:17)
    at initialize (http://localhost:3000/packages/astronomerio_core.js?76a17c3d39867f50b1a58d6adbfab9a6d50d3d79:10036:44)
    at runStartupCallbacks (http://localhost:3000/packages/meteor.js?e53378596562e8922a6369c955bab1e047fa866b:785:22)
    at HTMLDocument.ready (http://localhost:3000/packages/meteor.js?e53378596562e8922a6369c955bab1e047fa866b:787:3)
```

client side only.

Do you have have hangouts as I can be a little more responsive and help you debug this to get it fixed quicker ?

**Comment by ryw** [comment]
@robertpitt are you in our slack?

**Comment by robertpitt** [comment]
Yea I am on now thanks.

**Comment by ryw** [comment]
@schnie is this still open issue?

**Comment by schnie** [comment]
I think we're good.
